#Configuration File
file:
  save_pretty: false
debug: false
region:
  visitor: 'visitor'
  visitor_world: 'world'
  spawn: 'spawn'
  spawn_world: 'world'
targeting:
  max_range: 100
time_multiplier:
  daylight: 3
  night: 1
  worlds: [world]
home:
  enabled: true
landmark:
  enabled: true
  limit: 3
delivery_mob:
  enabled: false
  limit: 1
  invincible: true
  ghast:
    enabled: true