#Configuration File
persistence:
  file:
    format: 'json'
    pretty: false
  pdc:
    enabled: false
debug:
  enabled: false
member:
  enabled: true
  region:
    enabled: true
    visitor: 'visiting'
    visitor_world: 'world'
    spawn: 'spawn'
    spawn_world: 'world'
  home:
    enabled: true
time:
  enabled: true
  daylight: 3
  night: 1
  worlds: [world]
landmark:
  enabled: true
  limit: 3
locked_block:
  enabled: true
delivery:
  enabled: false
  limit: 1
  invincible: true
  ghast:
    enabled: true