name: PrivateReserve
main: me.hqm.privatereserve.PrivateReservePlugin
api-version: '1.15'
version: ${project.version}
description: Special sauce for HQM's private reserve.
authors: [HmmmQuestionMark]
depend: [Chitchat, WorldGuard]
commands:
  ## Everyday Commands
  nickname:
    usage: /nickname [username] <nickname>
    aliases: [nick]
  pronouns:
    usage: /pronouns [username] <pronouns>
  clearnickname:
    usage: /nickname [username]
    aliases: [clearnick]
  clearpronouns:
    usage: /pronouns [username]
  invite:
    usage: /invite [player]
  trust:
    usage: /trust [player]
  expel:
    usage: /expel [player]
  spawn:
    usage: /spawn
  visiting:
    usage: /visiting
    aliases: [vspawn]
  lockmode:
    usage: /lockmode
    aliases: [lock]
  memberhelp:
    usage: /memberhelp [topic]
  prdebug:
    usage: /prdebug
permisions:
  privatereserve.bypasslock:
    default: op
  privatereserve.admin:
    default: op
  privatereserve.self:
    default: true
