name: ReserveChat
main: me.hqm.privatereserve.PrivateReservePlugin
api-version: 1.15
version: ${project.version}
description: Special sauce for HQM's private reserve.
authors: [HmmmQuestionMark]
depend: [Chitchat]
commands:
  ## Everyday Commands
  nickname:
    usage: /nickname [username] <nickname>
    aliases: [nick]
  pronouns:
    usage: /pronouns [username] <pronouns>
  clearnickname:
    usage: /nickname [username]
    aliases: [clearnick]
  clearpronouns:
    usage: /pronouns [username]
permisions:
  reservechat.admin:
    default: op
  reservechat.self:
    default: true
