name: PrivateReserve
main: me.hqm.privatereserve.PrivateReserve
api-version: '1.21.8'
version: ${project.version}
description: Special sauce for HQM\'s private reserve.
authors: [HQM]
softdepend: [Chitchat, WorldGuard]
libraries:
  - org.msgpack:msgpack-core:${msgpack.version}
  - org.xerial.snappy:snappy-java:${snappy.version}
permisions:
  privatereserve.bypasslock:
    default: op
  privatereserve.admin:
    default: op
  privatereserve.self:
    default: true
